In [23]:
import numpy as np
import cv2

In [24]:
img = cv2.imread('lena.bmp')
type(img)


numpy.ndarray

In [25]:
img.shape

(512, 512, 3)

In [26]:
cv2.imshow('lena',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
img_gray = cv2.imread('lena.bmp', cv2.IMREAD_GRAYSCALE)

In [28]:
cv2.imshow('lena_gray',img_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
print(img)

[[[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 [[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 [[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 ...

 [[ 43  43  43]
  [ 43  43  43]
  [ 50  50  50]
  ...
  [104 104 104]
  [100 100 100]
  [ 98  98  98]]

 [[ 44  44  44]
  [ 44  44  44]
  [ 55  55  55]
  ...
  [104 104 104]
  [105 105 105]
  [108 108 108]]

 [[ 44  44  44]
  [ 44  44  44]
  [ 55  55  55]
  ...
  [104 104 104]
  [105 105 105]
  [108 108 108]]]


In [176]:
a = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [177]:
#a[0][0] = 123
#print(a)

In [178]:
b = np.reshape(a,(2,8))
print(b)


[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [179]:
b = np.reshape(a,(1,16))
print(b)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


In [180]:
#for i in range(5):
#    c = abs(i-5)
#    print(c) 
    


In [181]:
#b[0][1] = 1 
#print(b)

In [182]:
#for i in range(15):
#    b[0][i] = b[0][abs(i-15)]
#print(b)

In [183]:
#靠北 再開一個陣列

In [184]:
#c = np.array([(0),(16)])
#print(c)

#c = np.array([(0,1),(16,17)])
#print(c)

c = np.linspace(0,16,1)
c.resize(1,16)
print(c)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [185]:
for i in range(15):
    c[0][i] = b[0][abs(i-15)]
    print(c)

[[16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[16. 15.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[16. 15. 14.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[16. 15. 14. 13.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[16. 15. 14. 13. 12.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[16. 15. 14. 13. 12. 11.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[16. 15. 14. 13. 12. 11. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[16. 15. 14. 13. 12. 11. 10.  9.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[16. 15. 14. 13. 12. 11. 10.  9.  8.  0.  0.  0.  0.  0.  0.  0.]]
[[16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  0.  0.  0.  0.  0.  0.]]
[[16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  0.  0.  0.  0.  0.]]
[[16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.  0.  0.  0.  0.]]
[[16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.  4.  0.  0.  0.]]
[[16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.  4.  3.  0.  0.]]
[[16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5

In [186]:
c[0][15] = b[0][0]
print(c)

#絕對值那樣寫造成0的時候會變成[][]

[[16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]]


In [188]:
c = np.reshape(c,(4,4))
print(c)

[[16. 15. 14. 13.]
 [12. 11. 10.  9.]
 [ 8.  7.  6.  5.]
 [ 4.  3.  2.  1.]]


In [ ]:
#做出左右顛倒上下相反的圖片了~~~~~~~~~