In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('lena.bmp')
cv2.imshow('lena.bmp',img)
cv2.waitKey(0)

print(img)
img.shape

[[[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 [[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 [[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 ...

 [[ 43  43  43]
  [ 43  43  43]
  [ 50  50  50]
  ...
  [104 104 104]
  [100 100 100]
  [ 98  98  98]]

 [[ 44  44  44]
  [ 44  44  44]
  [ 55  55  55]
  ...
  [104 104 104]
  [105 105 105]
  [108 108 108]]

 [[ 44  44  44]
  [ 44  44  44]
  [ 55  55  55]
  ...
  [104 104 104]
  [105 105 105]
  [108 108 108]]]


(512, 512, 3)

In [3]:
storage_matrix = np.linspace(0,786432,1)
storage_matrix.resize(512,512,3)
print(storage_matrix)

storage_matrix.shape



[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


(512, 512, 3)

In [4]:
#data_array = np.zeros((3, 5, 6), dtype=np.int) #(row,column,channel),只是圖看起來不一樣

#print(data_array)

#data_array.shape

#data_array[0][2][4] = 5

#print(data_array)

#發現盲點! 下面矩陣呈現方式跟matlab不同ㄚㄚㄚㄚㄚ

In [5]:
a = np.zeros((4, 4, 3), dtype=np.int)

b = np.random.randint(0,10,size=[4,4,3]) #隨機整數矩陣

print(a)

print(b)


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[4 5 0]
  [5 1 1]
  [0 4 0]
  [8 2 9]]

 [[4 4 1]
  [9 3 8]
  [5 0 8]
  [3 6 6]]

 [[0 7 3]
  [0 5 1]
  [1 4 2]
  [5 9 1]]

 [[9 3 6]
  [6 4 1]
  [9 8 7]
  [9 5 8]]]


In [6]:
for j in range(3):
    for i in range(4):
        for k in range(4):
            a[i][k][j] = b[abs(i-4+1)][k][j]
            print(a)


[[[9 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[9 0 0]
  [6 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[9 0 0]
  [6 0 0]
  [9 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[9 0 0]
  [6 0 0]
  [9 0 0]
  [9 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[9 0 0]
  [6 0 0]
  [9 0 0]
  [9 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[9 0 0]
  [6 0 0]
  [9 0 0]
  [9 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0

In [7]:
for j in range(3):
    for i in range(512):
        for k in range(512):
            storage_matrix[i][k][j] = img[abs(i-512+1)][k][j]
print(storage_matrix)

[[[ 44.  44.  44.]
  [ 44.  44.  44.]
  [ 55.  55.  55.]
  ...
  [104. 104. 104.]
  [105. 105. 105.]
  [108. 108. 108.]]

 [[ 44.  44.  44.]
  [ 44.  44.  44.]
  [ 55.  55.  55.]
  ...
  [104. 104. 104.]
  [105. 105. 105.]
  [108. 108. 108.]]

 [[ 43.  43.  43.]
  [ 43.  43.  43.]
  [ 50.  50.  50.]
  ...
  [104. 104. 104.]
  [100. 100. 100.]
  [ 98.  98.  98.]]

 ...

 [[162. 162. 162.]
  [162. 162. 162.]
  [162. 162. 162.]
  ...
  [170. 170. 170.]
  [155. 155. 155.]
  [128. 128. 128.]]

 [[162. 162. 162.]
  [162. 162. 162.]
  [162. 162. 162.]
  ...
  [170. 170. 170.]
  [155. 155. 155.]
  [128. 128. 128.]]

 [[162. 162. 162.]
  [162. 162. 162.]
  [162. 162. 162.]
  ...
  [170. 170. 170.]
  [155. 155. 155.]
  [128. 128. 128.]]]


In [8]:
cv2.imwrite('new_image.bmp', storage_matrix)

new_image = cv2.imread('new_image.bmp')

cv2.imshow('new_image',new_image)

cv2.waitKey(0)

-1