In [153]:
import numpy as np
import cv2

In [154]:
def Oimgshow():
    img = cv2.imread('lena.bmp')
    cv2.imshow('img',img)
    cv2.waitKey(0)

In [155]:
#ratio = input('please input your zoom in/out ratio')
#print('your zoom in/out ratio', ratio) 

In [156]:
img = cv2.imread('lena.bmp')
np.shape(img)

print(img)

[[[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 [[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 [[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 ...

 [[ 43  43  43]
  [ 43  43  43]
  [ 50  50  50]
  ...
  [104 104 104]
  [100 100 100]
  [ 98  98  98]]

 [[ 44  44  44]
  [ 44  44  44]
  [ 55  55  55]
  ...
  [104 104 104]
  [105 105 105]
  [108 108 108]]

 [[ 44  44  44]
  [ 44  44  44]
  [ 55  55  55]
  ...
  [104 104 104]
  [105 105 105]
  [108 108 108]]]


In [157]:
#test
a = np.random.randint(10, size=(8,8,3))
b = np.zeros([4,8,3])
b2 = np.zeros([4,4,3])

for k in range(3):
    for j in range (8):
        for i in range (0,8,2):
            b[round(i/2)][j][k] = round((a[i][j][k]+a[i+1][j][k])/2) 
            
for k in range(3):
    for j in range (4):
        for i in range (0,8,2):
            b2[j][round(i/2)][k] = round((b[j][i][k]+b[j][i+1][k])/2) 
            
print(b2)

[[[5. 2. 5.]
  [8. 3. 6.]
  [2. 6. 5.]
  [4. 3. 3.]]

 [[7. 4. 6.]
  [3. 6. 5.]
  [4. 7. 3.]
  [5. 2. 4.]]

 [[4. 6. 4.]
  [6. 3. 2.]
  [2. 2. 3.]
  [6. 4. 4.]]

 [[6. 8. 5.]
  [6. 7. 4.]
  [2. 2. 2.]
  [5. 4. 6.]]]


In [158]:
#test end -> 用平均法沒問題啊

In [159]:
#create a tensor 
new_img = np.zeros([256,512,3])

for k in range(3):
    for j in range (512):
        for i in range (0,512,2):
            new_img[round(i/2)][j][k] = round(((img[i][j][k])/2+(img[i+1][j][k])/2)) 
            #會怪怪的原來是因為影像溢位阿(pixel 灰階值只能是0~255!,所以先相加會超過255,因此選擇先除2在相加)
                                              
print(new_img)
    

[[[162. 162. 162.]
  [162. 162. 162.]
  [162. 162. 162.]
  ...
  [170. 170. 170.]
  [155. 155. 155.]
  [128. 128. 128.]]

 [[162. 162. 162.]
  [162. 162. 162.]
  [162. 162. 162.]
  ...
  [170. 170. 170.]
  [155. 155. 155.]
  [128. 128. 128.]]

 [[163. 163. 163.]
  [163. 163. 163.]
  [160. 160. 160.]
  ...
  [147. 147. 147.]
  [129. 129. 129.]
  [102. 102. 102.]]

 ...

 [[ 51.  51.  51.]
  [ 51.  51.  51.]
  [ 52.  52.  52.]
  ...
  [ 92.  92.  92.]
  [ 91.  91.  91.]
  [ 92.  92.  92.]]

 [[ 44.  44.  44.]
  [ 44.  44.  44.]
  [ 50.  50.  50.]
  ...
  [103. 103. 103.]
  [ 99.  99.  99.]
  [ 97.  97.  97.]]

 [[ 44.  44.  44.]
  [ 44.  44.  44.]
  [ 55.  55.  55.]
  ...
  [104. 104. 104.]
  [105. 105. 105.]
  [108. 108. 108.]]]


In [160]:
new_img2 = np.zeros([256,256,3])

for k in range(3):
    for j in range (256):
        for i in range (0,512,2):
            new_img2[j][round(i/2)][k] = round((new_img[j][i][k])/2 + (new_img[j][i+1][k])/2 ) 
            #column好像沒有溢位的問題,但還是照做一下吧
print(new_img2)

[[[162. 162. 162.]
  [162. 162. 162.]
  [160. 160. 160.]
  ...
  [169. 169. 169.]
  [170. 170. 170.]
  [142. 142. 142.]]

 [[162. 162. 162.]
  [162. 162. 162.]
  [160. 160. 160.]
  ...
  [169. 169. 169.]
  [170. 170. 170.]
  [142. 142. 142.]]

 [[163. 163. 163.]
  [159. 159. 159.]
  [160. 160. 160.]
  ...
  [158. 158. 158.]
  [151. 151. 151.]
  [116. 116. 116.]]

 ...

 [[ 51.  51.  51.]
  [ 51.  51.  51.]
  [ 54.  54.  54.]
  ...
  [ 82.  82.  82.]
  [ 93.  93.  93.]
  [ 92.  92.  92.]]

 [[ 44.  44.  44.]
  [ 49.  49.  49.]
  [ 50.  50.  50.]
  ...
  [ 92.  92.  92.]
  [102. 102. 102.]
  [ 98.  98.  98.]]

 [[ 44.  44.  44.]
  [ 53.  53.  53.]
  [ 50.  50.  50.]
  ...
  [101. 101. 101.]
  [102. 102. 102.]
  [106. 106. 106.]]]


In [161]:
cv2.imwrite('shrink_lena_in_half.bmp',new_img2)
img = cv2.imread('shrink_lena_in_half.bmp')
cv2.imshow('shrink_lena_in_half',img)
cv2.waitKey(0)

-1