In [2]:
import numpy as np
import cv2

In [3]:
img = cv2.imread('lena.bmp')
cv2.imshow('lena',img)
cv2.waitKey(0)
#imshow 記得要add waitKey or dead
img.shape

#print(img)


[[[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 [[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 [[162 162 162]
  [162 162 162]
  [162 162 162]
  ...
  [170 170 170]
  [155 155 155]
  [128 128 128]]

 ...

 [[ 43  43  43]
  [ 43  43  43]
  [ 50  50  50]
  ...
  [104 104 104]
  [100 100 100]
  [ 98  98  98]]

 [[ 44  44  44]
  [ 44  44  44]
  [ 55  55  55]
  ...
  [104 104 104]
  [105 105 105]
  [108 108 108]]

 [[ 44  44  44]
  [ 44  44  44]
  [ 55  55  55]
  ...
  [104 104 104]
  [105 105 105]
  [108 108 108]]]


In [4]:
img_line = np.reshape(img,(1,786432,1))
print(img_line)

[[[162]
  [162]
  [162]
  ...
  [108]
  [108]
  [108]]]


In [5]:
storage_space = np.linspace(0,786432,1)
storage_space.resize(1,786432,1)
print(storage_space)

[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]]


In [11]:
for i in range (786431):
    storage_space[0][i][0] = img_line[0][abs(i-786431)][0]
storage_space[0][786431][0] = img_line[0][0][0]
new_image = np.reshape(storage_space,(512,512,3))
print(new_image)

#type(new_image)
#new_image.shape

cv2.imwrite('new_image.bmp', new_image)

new_image = cv2.imread('new_image.bmp')

cv2.imshow('new_image',new_image)

cv2.waitKey(0)


[[[108. 108. 108.]
  [105. 105. 105.]
  [104. 104. 104.]
  ...
  [ 55.  55.  55.]
  [ 44.  44.  44.]
  [ 44.  44.  44.]]

 [[108. 108. 108.]
  [105. 105. 105.]
  [104. 104. 104.]
  ...
  [ 55.  55.  55.]
  [ 44.  44.  44.]
  [ 44.  44.  44.]]

 [[ 98.  98.  98.]
  [100. 100. 100.]
  [104. 104. 104.]
  ...
  [ 50.  50.  50.]
  [ 43.  43.  43.]
  [ 43.  43.  43.]]

 ...

 [[128. 128. 128.]
  [155. 155. 155.]
  [170. 170. 170.]
  ...
  [162. 162. 162.]
  [162. 162. 162.]
  [162. 162. 162.]]

 [[128. 128. 128.]
  [155. 155. 155.]
  [170. 170. 170.]
  ...
  [162. 162. 162.]
  [162. 162. 162.]
  [162. 162. 162.]]

 [[128. 128. 128.]
  [155. 155. 155.]
  [170. 170. 170.]
  ...
  [162. 162. 162.]
  [162. 162. 162.]
  [162. 162. 162.]]]


-1